### ISSUE TITLE
Run at login time

### ISSUE THREAD

**Issue by sgourichon** [nullEuro/apply-equalizer#2]
Currently the user has to manually run the script.

Let's figure out how to have it run at login time.

This may be more or less desktop-environment dependent (I'm using XFCE on Ubuntu.) but thanks to freedesktop.org there's probably a common way.

My first guess: look in `/etc/xdg/autostart/` and add something there.

**Comment by nullEuro** [comment]
Hm yes that is probably the right place for this but I dont know how to force apply-equalizer.py to start _after_ pulseaudio itself. Would be nice to avoid a `sleep(10); ./apply-equalizer.py` hacky solution.

**Comment by sgourichon** [comment]
> Hm yes that is probably the right place for this but I dont know how 
> to force apply-equalizer.py to start /after/ pulseaudio itself. Would 
> be nice to avoid a |sleep(10); ./apply-equalizer.py| hacky solution.

How about having the script wait until dbus connection is available ?

**Comment by nullEuro** [comment]
Yes like pulseaudio-mixer does: https://github.com/mk-fg/pulseaudio-mixer-cli/blob/master/pulseaudio-mixer-cli.py#L74
