### ISSUE TITLE
Run as non-root: automatically adjust ~/.config/pulse/default.pa

### ISSUE THREAD

**Issue by sgourichon** [nullEuro/apply-equalizer#4]
For various reasons it is desirable to be able to run software as non-root. Example reasons: having several variants available for different users (e.g. developer using unstable version vs regular users wanting something less powerful that just works, or even the same user depending on time), systems where administrator cannot not approve that change quickly enough (security, policy, whatever).

Currently, this could mean that when 

```
        dbus.connection.Connection(srv_addr)
```

fails with

```
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /run/user/1000/pulse/dbus-socket: No such file or directory
```

The script automatically adds 

```
load-module module-dbus-protocol
```

to the _user's_ `~/.config/pulse/default.pa` after checking that it's not already there ?

```
        pa_config_path = os.path.join(xdg_config_home, 'pulse', 'default.pa')
        with open(pa_config_path, "a") as pa_config_fh:
            pa_config_fh.write("load-module module-dbus-protocol\n")
```

Checking to avoid duplicates is important else we break pulseaudio for the user...

**Comment by nullEuro** [comment]
Or we can go the direct way and check the output of

```
pactl list modules short
```

for `module-dbus-protocol`?

Maybe don't touch any configuration files at all and load the module if needed via pactr at startup time ourself?

**Comment by sgourichon** [comment]
> Maybe don't touch any configuration files at all and load the module if needed via pactr at startup time ourself?

That seems cleaner and safer.

I tested : removed my `~/.config/pulse/default.pa` (something went wrong and pulseaudio refused to start anyway), then it started okay then I did :

pactl load-module module-dbus-protocol

and run `./apply-equalizer.py` and it works.

So you approach is good.

**Comment by nullEuro** [comment]
This leads me to one more issue: apply-equalizer does not handle pulseaudio restarts and does not work anymore if you do `pulseaudio -k` (similar to the xfce-volumed bug...).

So at first I have to patch this.
